apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-version-statefulset
  labels:
    app: node-version
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: node-version
  serviceName: node-version
  template:
    metadata:
      labels:
        app: node-version
    spec:
      containers:
        - name: node-version
          image: jainishshah17/node-version:2.3.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "200Mi"
              cpu: "200m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              port: 3000
              path: /
              scheme: HTTP
            failureThreshold: 5
            successThreshold: 2
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              port: 3000
              path: /
              scheme: HTTP
            failureThreshold: 5
            successThreshold: 1
            initialDelaySeconds: 30
          volumeMounts:
            - mountPath: "/var/src/app/logs"
              name: logs
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
