apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: ci
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: ci
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
