apiVersion: v1
kind: Service
metadata:
  name: node-version-service
spec:
  selector:
    app: node-version
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
