apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-k8s
  template:
    metadata:
      labels:
        app: postgres-k8s
    spec:
      containers:
        - name: postgresql-k8s
          image: postgres:9.6
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-cred-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-cred-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cred-secret
                  key: password
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "500Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - mountPath: "/etc/foo"
              name: db-config
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
      volumes:
        - name: db-config
          secret:
            secretName: db-conf-secret

