apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgres-k8s
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-k8s
