apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-k8s-deployment
  labels:
    app: nginx-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-k8s-deployment
  template:
    metadata:
      labels:
        app: nginx-k8s-deployment
        group: artifactory-k8s-demo
    spec:
      containers:
      - name: nginx-k8s
        image: docker-dev-artifactory.workday.com/jainishshah/jfrog/nginx-artifactory-pro:6.18.0
        env:
        - name: ART_BASE_URL
          value: "http://artifactory:8081/artifactory"
        - name: SSL
          value: "true"
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        volumeMounts:
        - mountPath: "/var/opt/jfrog/nginx"
          name: nginx-volume
        - mountPath: "/var/opt/jfrog/nginx/ssl"
          name: ssl-secret-volume
      imagePullSecrets:
        - name: docker-reg-secret
      volumes:
      - name: nginx-volume
        persistentVolumeClaim:
          claimName: nginx-claim
      - name: ssl-secret-volume
        secret:
          secretName: art-tls
